name: Terraform validate

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/**'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform fmt (check)
        run: |
          terraform -version
          set -e
          find . -type f -name '*.tf' -not -path './.terraform/*' -print0 | xargs -0 -n1 dirname | sort -u | xargs -n1 -I{} sh -c 'cd "{}"; terraform fmt -check -diff'

  validate:
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init & validate
        run: |
          set -e
          find . -type f -name '*.tf' -not -path './.terraform/*' -print0 | xargs -0 -n1 dirname | sort -u | xargs -n1 -I{} sh -c 'cd "{}"; terraform init -backend=false -input=false >/dev/null; terraform validate'
